FROM __BASEIMAGE_ARCH__/alpine:latest

LABEL name='impulse'
LABEL version='0.2'
LABEL description='An endpoint checking service'
LABEL org.ctrlaltdev.vendor='ctrlaltdev'

__CROSS_COPY qemu-__QEMU_ARCH__-static /usr/bin/

RUN set -x && apk --no-cache add python3

WORKDIR /impulse

VOLUME /impulse/hosts
VOLUME /impulse/db

ADD db/* ./db/
ADD hosts/* ./hosts/
ADD impulse.py ./

RUN echo "* * * * * /impulse/impulse.py >> /dev/null" | crontab -

ENTRYPOINT [ "crond" ]